# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "licurry30"
repo_name: "CT-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/ct-arxiv-daily.json'
json_gitpage_path: './docs/ct-arxiv-daily-web.json'
json_wechat_path: './docs/ct-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "LDCT":
        filters: ["Low-Dose CT", "Computed Tomography", "Low Dose", "LDCT", "CT Denoising", "X-ray CT"]

    "SVCT":
        filters: ["Sparse-view CT","Compressed Sensing","Ultra Sparse-view CT","CT Reconstruction"]

    "GAN in CT":
        filters: [ "GAN","Generative Adversarial Networks","GAN for CT Reconstruction","GAN-based Denoising for CT"]

    "Diffusion in CT":
        filters: [ "Diffusion Models for CT Reconstruction","DDPM in CT","Diffusion Models for Sparse-view CT Reconstruction"]


